<?php

// module permissions
DEFINE('GENERAL_MODS_CREATE_OWN_BLOG', 'general_mods_create_blog');
DEFINE('GENERAL_MODS_ACCESS_ALL_BLOGS', 'general_mods_access_all_user_blogs');
DEFINE('GENERAL_MODS_ACCESS_OPEN_BLOGS', 'general_mods_access_open_blogs');

function general_mods_init() {
	global $user;
	if(arg(0) == 'node') {
		$node = menu_get_object();
		if($node && $node->type == 'blog'){
			if($user->uid != $node->uid && !user_access(GENERAL_MODS_ACCESS_ALL_BLOGS))
				_general_mods_deny_blog_access($node->uid);
			
			if($user->uid != $node->uid){
				$user_name = theme('username', array('account' => $user));
				$node_link = l($node->title, 'node/'.$node->nid);
				watchdog('general_mods', 'User !name viewed the blog page !blog_page', array('!name' => $user_name, '!blog_page' => $node_link));
			}
		}
	}
	
	if(arg(0) == 'blog'){
		$blog_owner_uid = arg(1);
		if($user->uid != $blog_owner_uid && !user_access(GENERAL_MODS_ACCESS_ALL_BLOGS)){
			_general_mods_deny_blog_access($blog_owner_uid);
		}
	}
	
	if(arg(0) == 'taxonomy' && arg(1) == 'term' && arg(3) == '') {
		if($user->uid != 1) {
			drupal_access_denied();
			module_invoke_all('exit');
			exit();
		}
	}
}

function general_mods_menu() {
	$items['custom/twitter'] = array(
		'page callback' => 'general_mods_twitter',
		'access callback' => TRUE,
		'file' => 'general_mods_twitter.inc',
	);
	
	return $items;
}

function _general_mods_deny_blog_access($blog_owner_uid = null){
	global $user;
	
	$blog_owner = user_load($blog_owner_uid);
	if(!$blog_owner)
		return;
	
	$private_blog = isset($blog_owner->data['general_mods_user_blog_privacy_setting']['value']) ? $blog_owner->data['general_mods_user_blog_privacy_setting']['value'] : 0;
	
	if($private_blog) {
		if(user_is_anonymous()) {
			drupal_set_message('Please login first to access this page.', 'warning');
			drupal_goto('user', array('query' => drupal_get_destination()));
		} else {
			drupal_set_message('The owner chose to not share this blog. Now, begone!', 'error');
			drupal_access_denied();
			module_invoke_all('exit');
			exit();
		}
	}

	//$current_user_blog_privacy = isset($user->data['general_mods_user_blog_privacy_setting']['value']) ? $user->data['general_mods_user_blog_privacy_setting']['value'] : 0;
	//if($current_user_blog_privacy) {
	//	// this user does not share his blog, do not allow this user to see other blogs
	//	drupal_set_message('You are not allowed to access other blogs because your own blog is private. Now, begone!', 'error');
	//	drupal_access_denied();
	//	module_invoke_all('exit');
	//	exit();
	//}
}

function general_mods_permission() {
  return array(
		GENERAL_MODS_CREATE_OWN_BLOG => array(
      'title' => t('Create own blog'),
      'description' => t('Create own blog'),
    ),
    GENERAL_MODS_ACCESS_ALL_BLOGS => array(
      'title' => t('Access ALL user blogs'),
      'description' => t('Access all user blogs'),
    ),
//		GENERAL_MODS_ACCESS_OPEN_BLOGS => array(
//      'title' => t('Access blogs shared by users'),
//      'description' => t('Access open blogs only'),
//    ),
  );
}

function general_mods_node_view_alter(&$build) {
	static $count = 0;
	
	$count++;
	
	$node = $build['#node'];
	if($node->type == 'blog'){
		// convert from teaser mode into full mode
		$build['body'][0]['#markup'] = $build['body']['#object']->body['und'][0]['safe_value'];
		if($count > 1)
			$build['#prefix'] = '<div class="line"></div>';
	}
}

function general_mods_form_alter(&$form, &$form_state, $form_id) {
	global $user;
	if($form_id == 'user_profile_form'){
		$user_loaded = $form['#user'];
		$collapsible_fields = array(
			'picture',
			'comment_notify_settings',
			'contact',
			'timezone',
		);
		
		foreach($collapsible_fields as $field_name) {
			if(isset($form[$field_name])){
				$form[$field_name]['#collapsible'] = TRUE;
				if($field_name == 'picture'){
					$form[$field_name]['#weight'] = 3;
				} else {
					$form[$field_name]['#weight'] = 50;
					$form[$field_name]['#collapsed'] = TRUE;
				}
			}
		}
		
		
		if(isset($form['account'])){
			$form['account']['#prefix'] = '<br /><div class="line"></div><br />';
		}
		
		$form['field_course']['#access'] = user_access(GENERAL_MODS_CREATE_OWN_BLOG);
		$form['field_year']['#access'] = user_access(GENERAL_MODS_CREATE_OWN_BLOG);
		
		$form['general_mods_blog_settings'] = array(
			'#type' => 'fieldset',
			'#title' => t('Blog privacy settings'),
			'#weight' => -50,
			//'#description' => t('Customize email message sent to users when their page revision has been approved.') . $email_token_help,
			'#access' => user_access(GENERAL_MODS_CREATE_OWN_BLOG),
		);
		
		$form['general_mods_blog_settings']['general_mods_user_blog_privacy_setting'] = array(
			'#type' => 'checkbox',
			'#title' => 'Private (only Teachers will see my posts)',
			//'#description' => 'You will not be able to see other students\' posts as well if you check this option.<br />You can only change this setting <em>every 48 hours</em>.',
			'#default_value' => isset($user_loaded->data['general_mods_user_blog_privacy_setting']['value']) ? $user_loaded->data['general_mods_user_blog_privacy_setting']['value'] : 0,			
		);
		
		//if(!user_access('administer users') && isset($user_loaded->data['general_mods_user_blog_privacy_setting']['last_changed'])) {
		//	$privacy_last_changed = $user_loaded->data['general_mods_user_blog_privacy_setting']['last_changed'];
		//	$form['general_mods_blog_settings']['general_mods_user_blog_privacy_setting']['#disabled'] = time() < strtotime('48 hours', $privacy_last_changed);
		//}
		
	}else if($form_id == 'blog_node_form'){
		$form['author']['#access'] = TRUE;
		if($user->uid != 1){
			$form['author']['name']['#disabled'] = TRUE;
			$form['author']['name']['#description'] = '';
		}
	}
}

function general_mods_preprocess_page(&$variables) {
	global $user;
	$hide_tabs = true;
	if((arg(0) == 'blog' || arg(0) == 'user') && is_numeric(arg(1))) {
		$blog_owner = user_load(arg(1));
		$full_name = theme('username', array('account' => $blog_owner));
		$page_title = strip_tags($full_name);
		if(arg(0) == 'blog'){
			$page_title .= ' \'s blog';
			$breadcrumbs = drupal_get_breadcrumb();
			if($breadcrumbs)
				$breadcrumbs = array($breadcrumbs[0]);
			$breadcrumbs[] = $full_name;
			drupal_set_breadcrumb($breadcrumbs);
		}
		
		drupal_set_title($page_title);
	}
	
	if(arg(0) == 'node'){
		$node = menu_get_object();
		if($node) {
			if($node->type == 'blog') {
				$full_name = theme('username', array('account' => $node));
				$full_name_plain = strip_tags($full_name);
				$page_title = $full_name_plain . ' \'s blog';
				drupal_set_title($page_title . ' <span>/ '. $node->title .'</span>', PASS_THROUGH);
				//$node->title = 'ss';
				
				$breadcrumbs = drupal_get_breadcrumb();
				if($breadcrumbs)
					$breadcrumbs = array($breadcrumbs[0]);
				$breadcrumbs[] = l($full_name_plain . ' \'s blog', 'blog/' . $node->uid);
				$breadcrumbs[] = $node->title;
				drupal_set_breadcrumb($breadcrumbs);
				
				if($node->uid == $user->uid)
					$hide_tabs = false;
			}
		}
	}
	
	if(arg(0) == 'contact'){
		drupal_set_message('If you have questions, bug findings, anything, let me know :)');
	}
	
	if($hide_tabs && $user->uid != 1){
		$variables['tabs']['#access'] = FALSE;
	}
}

function general_mods_user_presave(&$edit, $account, $category) {
	if(user_access(GENERAL_MODS_CREATE_OWN_BLOG)){
		$general_mods_user_blog_privacy_setting = isset($edit['general_mods_user_blog_privacy_setting']) ? $edit['general_mods_user_blog_privacy_setting'] : 0;
		$privacy_setting = array();
		$privacy_setting['value'] = $general_mods_user_blog_privacy_setting;
		if(user_access('administer users'))
			$privacy_setting['last_changed'] = 0;
		else if(!isset($edit['data']['general_mods_user_blog_privacy_setting']['value']) || $edit['data']['general_mods_user_blog_privacy_setting']['value'] != $general_mods_user_blog_privacy_setting)
			$privacy_setting['last_changed'] = time();
			
		$edit['data']['general_mods_user_blog_privacy_setting'] = $privacy_setting;
	}
}